default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: gdburky
  password:
  pool: 5

development:
  <<: *default
  database: ejemplo1


test:
  <<: *default
  database: ejemplo1
